apiVersion: v1
kind: ConfigMap
metadata:
  name: "spherexportal"
  labels:
    app.kubernetes.io/name: "spherex-doc-portal"
data:
  # These configurations are injected as environment variables into the
  # app container.
  SAFIR_NAME: "spherexportal"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "spherexportal"
  SAFIR_LOG_LEVEL: "INFO"
