apiVersion: v1
kind: ConfigMap
metadata:
  name: "spherex-doc-portal"
  labels:
    app.kubernetes.io/name: "spherex-doc-portal"
data:
  # These configurations are injected as environment variables into the
  # app container.
  SAFIR_NAME: "spherexportal"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "spherexportal"
  SAFIR_LOG_LEVEL: "INFO"
  PORTAL_DATASET_PATH: "/opt/spherex-doc-portal/dataset/dataset.yaml"
  PORTAL_REDIS_URL: "redis://redis:6379/0"
  PORTAL_ARQ_REDIS_URL: "redis://redis:6379/1"
  PORTAL_ARQ_MODE: "production"
