apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "ghcr.io/spherex/spherex-doc-portal"
    newTag: 0.0.0

resources:
  - configmap.yaml
  - dataset-configmap.yaml
  - deployment.yaml
  - worker.yaml
  - service.yaml
