apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "ghcr.io/jsickcodes/spherexportal"
    newTag: 0.0.0

resources:
  - configmap.yaml
  - dataset-configmap.yaml
  - deployment.yaml
  - service.yaml
