apiVersion: v1
kind: Service
metadata:
  name: "spherexportal"
  labels:
    app.kubernetes.io/name: "spherex-doc-portal"
spec:
  ports:
    - name: "spherexportal-http"
      protocol: "TCP"
      port: 8080
      targetPort: "app"
  selector:
    app.kubernetes.io/name: "spherexportal"
